STICKERS = [
    "CAACAgIAAxkBAAIXKmP_wt57GT92DcaU43nQw8S5xyTdAAKvJQACm6JwS7g5xX27XghmHgQ",
    "CAACAgUAAxkBAAIXLGP_wv0azEjRsGMJJES1bqC0vHIIAALIBwACTDaYV8VOMbFmOAf2HgQ",
    "CAACAgUAAxkBAAIXLmP_wweokBARXWU5T8m02Kky7RwPAAIaCgAC-lRxVyvUncXmz-R4HgQ",
    "CAACAgIAAxkBAAIXMGP_wxPyQ9jwmZwAAf2k3X1N3oARMAACzQEAAhZCawrL2Zt7FoIvuB4E",
    "CAACAgIAAxkBAAIXMmP_wx_lpTs1LDq2iK_8Bd-OWSfYAAKfAQACFkJrCmWMf9oXSSAlHgQ",
    "CAACAgIAAxkBAAIXNGP_wygbuIU3iFs_5R8NIR5NO2X_AAJyEgACRuWpSPJMG0U-1wNRHgQ",
    "CAACAgIAAxkBAAIXNmP_wyw5u4x66TVRbUdnB0JoYkNaAAKjDgAC1rIwSRpDkGil29d8HgQ",
    "CAACAgIAAxkBAAIXOGP_wz2I2KijIQWGQZuySPYAAV81WwACRAADKA9qFFts_7_cyqtAHgQ",
    "CAACAgIAAxkBAAIXOmP_w0exI9_75n2sZ0BpzRbgYVA4AAIEAQAC9wLIDyAPdzvpq8hJHgQ",
    "CAACAgQAAxkBAAIXPGP_w00ySHSQBgjOiKWJxSu7clOjAALqCwACbCIRU61ZQKi3F88DHgQ",
    "CAACAgQAAxkBAAIXPmP_w1c-meLecHvVteL0IqUUmvxoAAK9CQACelwRUzpqVCTmeOrfHgQ",
]
